### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by RowinRuizendaal** [Vuurvos1/functional-programming#1]
Suggestions insights:

#### Research question

Not sure if you want to change your research question to a parking spot? Or what do you mean by location available spots? specific days? whole week? My suggestions would be: make it something more specific

#### Datasets needed

Datasets are looking good, maybe document it for yourself where you can merge the two different datasets together, as in primary keys, I think you are going to use AreadId?

Did you find a dataset for 'how many parking spots are filled' or are you still searching for this one? Or do you need help to find that specific dataset?

#### Assumptions

Maybe there are less parking spots available during the Dutch holidays (Christmas, Easter, Sinterklaas, etc)

Maybe you have a bigger chance of finding a **paid** parking spot than a free parking spot throughout the week

Keep it up, hopefully, my feedback is something useful (☞ﾟヮﾟ)☞☜(ﾟヮﾟ☜)

**Comment by Vuurvos1** [comment]
Thanks for the feedback (☞ﾟヮﾟ)☞☜(ﾟヮﾟ☜)
