### ISSUE TITLE
peer review wiki

### ISSUE THREAD

**Issue by jor-s** [Vuurvos1/functional-programming#3]
Repo+Readme
- [x] gitignore?
- [x] no node_modules or other junk included in the uploaded files? 
- [x] repo description?
- [ ] concept described in readme? Research question, data to be used, sketch of datavisualization.
Don't see any sketches yet. Maybe you could show which values of each dataset you are going to use?
- [x] data used described properly? (what's done with invalid and empty values?)
- [ ] link to most interesting functional pattern
- [x] plagiarism and acknowledgements
I see a list of sources whenever you use information from the web. 

Wiki
- [x] debrief of assignment? 
- [ ] datacleaning and transforming process described?
No transforming *yet*
- [x] clear which functional patterns are applied in the code?
- [x] Do you see any improvements? 
I see iterations, you are doing well!
- [x] try to understand the code flow
- [ ] Is the most important code at the top?
There isn't any code highlighted at the moment.
- [x] Is everything split into functions? Are other principles of functional programming applied?
- [x] Are map/forEach used in the right way?
- [x] Code comments for explaining the function
- [x] Be sure to check code quality (is it functional, consistency, reusability, naming conventions etc.)

Overall, you are doing a great job!

**Comment by Vuurvos1** [comment]
Thanks for the feedback! Implemented the missing things
